version: "3.9"

services:
  mail:
    image: bytemark/smtp
    restart: always
    environment:
      RELAY_HOST: smtp.gmail.com
      RELAY_PORT: 587
      RELAY_USERNAME: Coloca o email
      RELAY_PASSWORD: Coloca a senha
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: compras
    volumes:
      - db_data:/var/lib/mysql
      - ./schemas:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  web:
    image: webdevops/php-apache:8.2-alpine
    ports:
      - "8080:80"
    volumes:
      - ./comeco:/app
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "4500:80"
    dns:
      - 8.8.8.8
      - 8.8.4.4
volumes:
  db_data:
